-- 1. Run this SQL in your Supabase Dashboard SQL Editor to create the missing table.

CREATE TABLE public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    message TEXT NOT NULL
);

-- 2. Enable Row Level Security
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 3. Allow anonymous users to SEND messages
CREATE POLICY "Allow anonymous inserts" ON public.messages
    FOR INSERT 
    WITH CHECK (true);

-- Note: No SELECT policy is added for anon, so users can't read other people's messages.
